openapi: 3.0.1
info:
  title: Back-office Planning System
  version: v1
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  '/api/v1/planning_applications/{id}':
    get:
      summary: Retrieves all determined planning applications
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minimum: 1
          description: The planning application ID
      responses:
        '200':
          description: All determined planning applications
          content:
            application/json:
              examples:
                Full:
                  value:
                    id: 10000
                    application_number: '00010000'
                    site:
                      address_1: 11 Abbey Gardens
                      address_2: Southwark
                      town: nil
                      county: London
                      postcode: SE16 3RQ
                      uprn: '100081043511'
                    status: not_started
                    application_type: lawfulness_certificate
                    description: Add chimnney stack
                    created_at: '2020-05-14T06:18:17.540+01:00'
                    received_date: '2020-05-14T06:18:17.540+01:00'
                    determined_at: '2020-05-14T06:18:17.540+01:00'
                    target_date: '2020-07-02'
                    started_at: '2020-05-15T06:18:17.540+01:00'
                    invalidated_at: null
                    withdrawn_at: null
                    returned_at: null
                    work_status: proposed
                    payment_reference: PAY1
                    payment_amount: 10500
                    awaiting_determination_at: '2020-05-16T06:18:17.540+01:00'
                    in_assessment_at: '2020-05-16T06:18:17.540+01:00'
                    awaiting_correction_at: null
                    applicant_first_name: Albert
                    applicant_last_name: Manteras
                    agent_first_name: Jennifer
                    agent_last_name: Harper
                    agent_phone: '237878889'
                    agent_email: agent@example.com
                    result_flag: Planning permission / Permission needed
                    result_heading: It looks like these changes will need planning permission
                    result_description: 'Based on the information you have provided, we do not think this is eligible for a Certificate of Lawfulness'
                    result_override: This was my reason for rejecting the result
                    constraints:
                      - Conservation Area
                      - Listed Building
                    boundary_geojson:
                      type: Feature
                      geometry:
                        type: Polygon
                        coordinates:
                          - - - -0.07716178894042969
                              - 51.50094238217541
                            - - -0.07645905017852783
                              - 51.50053497847238
                            - - -0.07615327835083008
                              - 51.50115276135022
                            - - -0.07716178894042969
                              - 51.50094238217541
                    documents:
                      - url: 'http://example.com/document_path.pdf'
                        created_at: '2020-05-16T06:18:17.540+01:00'
                        tags:
                          - Side
                          - Elevation
                          - Proposed
                        numbers: PLAN01
                        applicant_description: This is the proposed side elevation
  /api/v1/planning_applications:
    get:
      summary: Retrieves all determined planning applications
      responses:
        '200':
          description: All determined planning applications
          content:
            application/json:
              examples:
                Full:
                  value:
                    data:
                      - id: 10000
                        application_number: '00010000'
                        site:
                          address_1: 11 Abbey Gardens
                          address_2: Southwark
                          town: nil
                          county: London
                          postcode: SE16 3RQ
                          uprn: '100081043511'
                        status: not_started
                        application_type: lawfulness_certificate
                        description: Add chimnney stack
                        created_at: '2020-05-14T06:18:17.540+01:00'
                        received_date: '2020-05-14T06:18:17.540+01:00'
                        determined_at: '2020-05-14T06:18:17.540+01:00'
                        target_date: '2020-07-02'
                        started_at: '2020-05-15T06:18:17.540+01:00'
                        invalidated_at: null
                        withdrawn_at: null
                        returned_at: null
                        work_status: proposed
                        payment_reference: PAY1
                        payment_amount: 10500
                        awaiting_determination_at: '2020-05-16T06:18:17.540+01:00'
                        in_assessment_at: '2020-05-16T06:18:17.540+01:00'
                        awaiting_correction_at: null
                        applicant_first_name: Albert
                        applicant_last_name: Manteras
                        agent_first_name: Jennifer
                        agent_last_name: Harper
                        agent_phone: '237878889'
                        agent_email: agent@example.com
                        result_flag: Planning permission / Permission needed
                        result_heading: It looks like these changes will need planning permission
                        result_description: 'Based on the information you have provided, we do not think this is eligible for a Certificate of Lawfulness'
                        result_override: This was my reason for rejecting the result
                        constraints:
                          - Conservation Area
                          - Listed Building
                        boundary_geojson:
                          type: Feature
                          geometry:
                            type: Polygon
                            coordinates:
                              - - - -0.07716178894042969
                                  - 51.50094238217541
                                - - -0.07645905017852783
                                  - 51.50053497847238
                                - - -0.07615327835083008
                                  - 51.50115276135022
                                - - -0.07716178894042969
                                  - 51.50094238217541
                        documents:
                          - url: 'http://example.com/document_path.pdf'
                            created_at: '2020-05-16T06:18:17.540+01:00'
                            tags:
                              - Side
                              - Elevation
                              - Proposed
                            numbers: PLAN01
                            applicant_description: This is the proposed side elevation
    post:
      summary: Create new planning application
      security:
        - bearerAuth: []
      parameters: []
      responses:
        '200':
          description: valid_request
          content: {}
        '400':
          description: invalid_request
          content: {}
        '401':
          description: unauthorized_user
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                application_type:
                  type: string
                  enum:
                    - lawfulness_certificate
                  example: lawfulness_certificate
                site:
                  type: object
                  properties:
                    uprn:
                      type: string
                      example: '100081043511'
                    address_1:
                      type: string
                      example: 11 Abbey Gardens
                    address_2:
                      type: string
                      example: Southwark
                    town:
                      type: string
                      example: London
                    postcode:
                      type: string
                      example: SE16 3RQ
                description:
                  type: string
                  example: Add chimnney stack
                payment_reference:
                  type: string
                  example: PAY1
                payment_amount:
                  type: integer
                  example: 10300
                work_status:
                  type: string
                  example: proposed
                proposal_details:
                  type: array
                  items:
                    type: object
                    properties:
                      question:
                        type: string
                        example: what are you planning to do?
                      responses:
                        type: array
                        items:
                          type: object
                          properties:
                            value:
                              type: string
                              example: demolish
                            metadata:
                              type: object
                              properties:
                                flags:
                                  type: array
                                  items:
                                    type: object
                                    properties:
                                      value:
                                        type: string
                                        example: Planning permission / Permission needed
                      metadata:
                        type: object
                        properties:
                          notes:
                            type: string
                            example: this will be done before rebuilding
                          auto_answered:
                            type: boolean
                            example: true
                          policy_refs:
                            type: array
                            items:
                              type: object
                              properties:
                                url:
                                  type: string
                                  example: 'http://example.com/planning/policy/1/234/a.html'
                                value:
                                  type: string
                                  example: GPDO 32.2342.223
                          flags:
                            type: array
                            items:
                              type: object
                              properties:
                                value:
                                  type: string
                agent_first_name:
                  type: string
                  example: Jennifer
                agent_last_name:
                  type: string
                  example: Harper
                agent_phone:
                  type: string
                  example: '237878889'
                agent_email:
                  type: string
                  example: agent@example.com
                applicant_first_name:
                  type: string
                  example: Albert
                applicant_last_name:
                  type: string
                  example: Manteras
                applicant_phone:
                  type: string
                  example: '23432325435'
                applicant_email:
                  type: string
                  example: applicant@example.com
                result:
                  type: object
                  properties:
                    flag:
                      type: string
                      example: Planning permission / Permission needed
                    heading:
                      type: string
                      example: It looks like these changes will need planning permission
                    description:
                      type: string
                      example: 'Based on the information you have provided, we do not think this is eligible for a Certificate of Lawfulness'
                    override:
                      type: string
                      example: This was my reason for rejecting the result
                constraints:
                  type: object
                files:
                  type: array
                  items:
                    type: object
                    properties:
                      filename:
                        type: string
                        example: 'https://bops-test.s3.eu-west-2.amazonaws.com/proposed-first-floor-plan.pdf'
                      tags:
                        type: array
                        items:
                          type: string
                          example: Side
                      applicant_description:
                        type: string
                        example: This is the side plan
                boundary_geojson:
                  type: object
              required:
                - site
                - application_type
                - applicant_email
            examples:
              Minimum:
                value:
                  application_type: lawfulness_certificate
                  site:
                    uprn: '100081043511'
                    address_1: 11 Abbey Gardens
                    address_2: Southwark
                    town: London
                    postcode: SE16 3RQ
                  applicant_email: applicant@example.com
              Full:
                value:
                  application_type: lawfulness_certificate
                  site:
                    uprn: '100081043511'
                    address_1: 11 Abbey Gardens
                    address_2: Southwark
                    town: London
                    postcode: SE16 3RQ
                  description: Add a chimney stack
                  payment_reference: PAY1
                  payment_amount: 10300
                  work_status: proposed
                  applicant_first_name: Albert
                  applicant_last_name: Manteras
                  applicant_phone: '23432325435'
                  applicant_email: applicant@example.com
                  agent_first_name: Jennifer
                  agent_last_name: Harper
                  agent_phone: '237878889'
                  agent_email: agent@example.com
                  result:
                    flag: Planning permission / Permission needed
                    heading: It looks like these changes will need planning permission
                    description: 'Based on the information you have provided, we do not think this is eligible for a Certificate of Lawfulness'
                    override: This was my reason for rejecting the result
                  proposal_details:
                    - question: What do you want to do?
                      responses:
                        - value: Modify or extend
                    - question: What is the dwelling used as?
                      responses:
                        - value: A family home
                    - question: Is the property a house?
                      responses:
                        - value: 'Yes'
                    - question: How many storeys will the new structure have?
                      responses:
                        - value: '1'
                    - question: Was the house always a house?
                      responses:
                        - value: 'Yes'
                    - question: Will the structure include a satellite dish or antenna?
                      responses:
                        - value: 'No'
                      metadata:
                        policy_refs:
                          - url: 'http://example.com/planning/policy/1/234/a.html'
                            text: GPDO 00.0000.000
                    - question: What will be the total footprint of all additions of the available area around the original house?
                      responses:
                        - value: 50% or less
                    - question: How high will the eaves of the new structure be?
                      responses:
                        - value: 2.5m or lower
                    - question: What will the height of the new structure be?
                      responses:
                        - value: 2.5m or lower
                    - question: How close will the new structure be to the site boundary?
                      responses:
                        - value: Within 2m
                    - question: Will any part of the new structure be forward of the front of the original house?
                      responses:
                        - value: 'No'
                    - question: Will any part of the pool be forward of the front of the original house?
                      responses:
                        - value: 'No'
                    - question: What is the addition to the property?
                      responses:
                        - value: An outdoor pool
                        - value: An outbuilding
                      metadata:
                        policy_refs:
                          - url: 'http://example.com/planning/policy/1/234/b.html'
                            text: GPDO 00.0000.000
                          - url: 'http://example.com/planning/policy/1/234/c.html'
                            text: GPDO 00.0000.000
                    - question: How many storeys will the new structure have?
                      responses:
                        - value: '1'
                    - question: Is the property on designated land?
                      responses:
                        - value: 'No'
                          auto_answered: true
                    - question: Is the property in an area of outstanding natural beauty?
                      responses:
                        - value: 'No'
                      metadata:
                        auto_answered: true
                    - question: Is the property in the broads?
                      responses:
                        - value: 'No'
                      metadata:
                        auto_answered: true
                    - question: Is the property in a world heritage site?
                      responses:
                        - value: 'No'
                      metadata:
                        auto_answered: true
                    - question: Is the property in a national park?
                      responses:
                        - value: 'No'
                      metadata:
                        auto_answered: true
                    - question: Is any part of the property listed?
                      responses:
                        - value: 'No'
                          metadata:
                            flags:
                              - Listed building consent / Not required
                    - question: Will the works affect a protected tree?
                      responses:
                        - value: 'No'
                      metadata:
                        auto_answered: true
                    - question: Will the new addition allow you to do an activity that most houses do not provide a dedicated space for?
                      responses:
                        - value: 'Yes'
                          metadata:
                            notes: It will allow me to exercise on a regular basis and generate energy
                            flags:
                              - Planning permission / Permission needed
                  constraints:
                    conservation_area: true
                    protected_trees: false
                  files:
                    - filename: 'https://bops-test.s3.eu-west-2.amazonaws.com/proposed-first-floor-plan.pdf'
                      applicant_description: This is the side plan
                      tags:
                        - Side
                  boundary_geojson:
                    type: Feature
                    geometry:
                      type: Polygon
                      coordinates:
                        - - - -0.07716178894042969
                            - 51.50094238217541
                          - - -0.07645905017852783
                            - 51.50053497847238
                          - - -0.07615327835083008
                            - 51.50115276135022
                          - - -0.07716178894042969
                            - 51.50094238217541
  '/api/v1/planning_applications/{planning_application_id}/validation_requests':
    get:
      summary: Retrieves all validation requests for a given planning application
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: planning_application_id
          required: true
          schema:
            type: integer
            minimum: 1
          description: The planning application ID
        - in: query
          name: change_access_id
          schema:
            type: string
          required: true
          description: A unique access code for this planning application
      responses:
        '200':
          description: All validation requests
          content:
            application/json:
              examples:
                Full:
                  value:
                    data:
                      description_change_validation_requests:
                        - id: 1
                          type: description_change_validation_request
                          proposed_description: A proposed new description
                          state: open
                          response_due: '2020-05-14T05:18:17.540Z'
                          days_until_response_due: 10
                          approved: true
                          rejection_reason: nil
                      replacement_document_validation_requests:
                        - id: 2
                          type: replacement_document_validation_request
                          state: open
                          response_due: '2020-05-14T05:18:17.540Z'
                          days_until_response_due: 10
                          old_document:
                            name: document.jpg
                            invalid_document_reason: It is missing a scale
                          new_document:
                            name: new_document.jpg
                            url: document.blob./new_document.jpg
  '/api/v1/planning_applications/{planning_application_id}/description_change_validation_requests/{description_change_validation_request_id}':
    patch:
      summary: Update a description validation request
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: planning_application_id
          required: true
          schema:
            type: integer
            minimum: 1
          description: The planning application ID
        - in: path
          name: description_change_validation_request_id
          required: true
          schema:
            type: integer
            minimum: 1
          description: The validation request ID
        - in: query
          name: change_access_id
          schema:
            type: string
          required: true
          description: A unique access code for this planning application
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                approved:
                  type: boolean
                  example: true
                rejection_reason:
                  type: string
                  example: Refusal reason
              required:
                - approved
            examples:
              Accept:
                value:
                  data:
                    approved: true
              Reject:
                value:
                  data:
                    approved: false
                    rejection_reason: Refusal reason
      responses:
        '200':
          description: Update description change validation request
          content:
            application/json:
              examples:
                Accept:
                  value:
                    message:
                      - Validation request updated
  '/api/v1/planning_applications/{planning_application_id}/replacement_document_validation_requests/{replacement_document_validation_request_id}':
    patch:
      summary: Update a document change validation request
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: planning_application_id
          required: true
          schema:
            type: integer
            minimum: 1
          description: The planning application ID
        - in: path
          name: replacement_document_validation_request_id
          required: true
          schema:
            type: integer
            minimum: 1
          description: The validation request ID
        - in: query
          name: change_access_id
          schema:
            type: string
          required: true
          description: A unique access code for this planning application
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                new_file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Update document change validation request
          content:
            application/json:
              examples:
                Accept:
                  value:
                    message:
                      - Validation request updated
  '/api/v1/planning_applications/{planning_application_id}/additional_document_validation_requests/{additional_document_validation_request_id}':
    patch:
      summary: Update a document create request
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: planning_application_id
          required: true
          schema:
            type: integer
            minimum: 1
          description: The planning application ID
        - in: path
          name: additional_document_validation_request_id
          required: true
          schema:
            type: integer
            minimum: 1
          description: The validation request ID
        - in: query
          name: change_access_id
          schema:
            type: string
          required: true
          description: A unique access code for this planning application
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                new_file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Update additional document validation request
          content:
            application/json:
              examples:
                Accept:
                  value:
                    message:
                      - Validation request updated
  '/api/v1/planning_applications/{planning_application_id}/red_line_boundary_change_validation_requests/{red_line_boundary_change_id}':
    patch:
      summary: Update a red line boundary change validation request
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: planning_application_id
          required: true
          schema:
            type: integer
            minimum: 1
          description: The planning application ID
        - in: path
          name: red_line_boundary_change_id
          required: true
          schema:
            type: integer
            minimum: 1
          description: The validation request ID
        - in: query
          name: change_access_id
          schema:
            type: string
          required: true
          description: A unique access code for this planning application
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                approved:
                  type: boolean
                  example: true
                rejection_reason:
                  type: string
                  example: Refusal reason
              required:
                - approved
            examples:
              Accept:
                value:
                  data:
                    approved: true
              Reject:
                value:
                  data:
                    approved: false
                    rejection_reason: Refusal reason
      responses:
        '200':
          description: Update red line boundary change validation request
          content:
            application/json:
              examples:
                Accept:
                  value:
                    message:
                      - Validation request updated
